library verilog;
use verilog.vl_types.all;
entity Datapath is
    port(
        IR_value        : out    vl_logic_vector(31 downto 0);
        MDR_value       : out    vl_logic_vector(31 downto 0);
        CON_FF          : out    vl_logic;
        OutPort_value   : out    vl_logic_vector(31 downto 0);
        PCout           : in     vl_logic;
        MDRout          : in     vl_logic;
        Zlowout         : in     vl_logic;
        Zhighout        : in     vl_logic;
        HIout           : in     vl_logic;
        LOout           : in     vl_logic;
        InPortout       : in     vl_logic;
        Cout            : in     vl_logic;
        Gra             : in     vl_logic;
        Grb             : in     vl_logic;
        Grc             : in     vl_logic;
        Rin             : in     vl_logic;
        Rout            : in     vl_logic;
        BAout           : in     vl_logic;
        PCin            : in     vl_logic;
        PCinIfCON       : in     vl_logic;
        IRin            : in     vl_logic;
        MARin           : in     vl_logic;
        MDRin           : in     vl_logic;
        Yin             : in     vl_logic;
        Zin             : in     vl_logic;
        HIin            : in     vl_logic;
        LOin            : in     vl_logic;
        CONin           : in     vl_logic;
        OutPortin       : in     vl_logic;
        IncPC           : in     vl_logic;
        ADD             : in     vl_logic;
        SUB             : in     vl_logic;
        AND_op          : in     vl_logic;
        OR_op           : in     vl_logic;
        SHR             : in     vl_logic;
        SHRA            : in     vl_logic;
        SHL             : in     vl_logic;
        \ROR\           : in     vl_logic;
        \ROL\           : in     vl_logic;
        NEG             : in     vl_logic;
        NOT_op          : in     vl_logic;
        MUL             : in     vl_logic;
        DIV             : in     vl_logic;
        Read            : in     vl_logic;
        Write           : in     vl_logic;
        InPortData      : in     vl_logic_vector(31 downto 0);
        InPortStrobe    : in     vl_logic;
        Clock           : in     vl_logic;
        Clear           : in     vl_logic
    );
end Datapath;
