library verilog;
use verilog.vl_types.all;
entity control_unit is
    port(
        PCout           : out    vl_logic;
        MDRout          : out    vl_logic;
        Zlowout         : out    vl_logic;
        Zhighout        : out    vl_logic;
        HIout           : out    vl_logic;
        LOout           : out    vl_logic;
        InPortout       : out    vl_logic;
        Cout            : out    vl_logic;
        Gra             : out    vl_logic;
        Grb             : out    vl_logic;
        Grc             : out    vl_logic;
        Rin             : out    vl_logic;
        Rout            : out    vl_logic;
        BAout           : out    vl_logic;
        PCin            : out    vl_logic;
        PCinIfCON       : out    vl_logic;
        IRin            : out    vl_logic;
        MARin           : out    vl_logic;
        MDRin           : out    vl_logic;
        Yin             : out    vl_logic;
        Zin             : out    vl_logic;
        HIin            : out    vl_logic;
        LOin            : out    vl_logic;
        CONin           : out    vl_logic;
        OutPortin       : out    vl_logic;
        IncPC           : out    vl_logic;
        ADD             : out    vl_logic;
        SUB             : out    vl_logic;
        AND_op          : out    vl_logic;
        OR_op           : out    vl_logic;
        SHR             : out    vl_logic;
        SHRA            : out    vl_logic;
        SHL             : out    vl_logic;
        \ROR\           : out    vl_logic;
        \ROL\           : out    vl_logic;
        NEG             : out    vl_logic;
        NOT_op          : out    vl_logic;
        MUL             : out    vl_logic;
        DIV             : out    vl_logic;
        Read            : out    vl_logic;
        Write           : out    vl_logic;
        Clear           : out    vl_logic;
        Run             : out    vl_logic;
        IR              : in     vl_logic_vector(31 downto 0);
        MDR_value       : in     vl_logic_vector(31 downto 0);
        Clock           : in     vl_logic;
        Reset           : in     vl_logic;
        Stop            : in     vl_logic;
        CON_FF          : in     vl_logic
    );
end control_unit;
